### ISSUE TITLE
Asking Questions To Customer About Practice App

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#101]
Emilcan will ask questions about web page to customer. 
_Deadline: 08.05.2020_

**Comment by UkcaGreen** [comment]
Related mail is sent. Questions that are asked are listed below.

1. How detailed should the frontend be?
- Just a one-page application is enough or should it contains multiple pages?
- Are login and signup functionalities are necessary?
- Are we allowed to use and modify ready templates in order to speed up the development process?
2. What functionalities should our REST API support?
- What are the "musts" that need to be implemented?
- Should the content of the external API returned as it is? Or do we have to manipulate the data we get from there?
