### ISSUE TITLE
Mock Data Creation

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#188]
Mock Data will be prepared for presentation.
Deadline: 22/11/2020 23.59

**Comment by cemreefe** [comment]
I am going to create mock data for the following fields:
Please object to any missing or wrong fields.

**sign-up**
* `name`, `surname`
* `e-mail`
* `password`

**personal information**
* `affiliation`
* `research area interests`

**project creation**
* `project title`
* `project summary`
* `deadline`
* `privacy`
* `tags`

**search**
* `search query`
* three projects: `title`, `abstract`
* three people: `name`, `surname`, `affiliation`

**Comment by cemreefe** [comment]
I am going to create mock data for the following fields:
Please object to any missing or wrong fields.

**user**
* `name`: Leyla
* `surname`: Özokutan
* `e-mail`: **to be generated from tempmail**
* `password`: Lokutan1

**personal information**
* `affiliation`: 
  * `university`: Boğaziçi University
  * `department`: Cognitive Science
  * `degree`: MSc
* `research area interests`: Computer Science, Philosophy, Psychology

**project creation**
* `project title`: Using Computer Science as a Means to Teach Immaterial Formal Logic
* `project summary`:  If all of life is governed by logic, as Paul Weiss posits, why should mathematics be different? Why is it not universal and immaterial as well? I will show how the use of other forms of logic, especially fiction and fantasy literature, can help students to come to terms with immateriality, or the need to treat it, even to process it, as a fact of life rather than as something hidden, or even, perversely, treated as a problem of semantics.
* `deadline`: July 21st, 2021
* `privacy`: public
* `tags`: Education, Logic, Computer Science

**search**
* `search query`: network, spectrum, raman
* projects that already should be in the database: `title`, `abstract`:
  * **An LTE-WiFi Spectrum Aggregation System for 5G Network: A Testbed**:
  `abstract`: Nowadays, the continuous increase in the high data traffic demand and providing the different quality of services (QOS) to the customer is a very challenging task for all network operators. In the last few years, mobile data traffic is increased to a significant extent. To overcome the increasing traffic demand WiFi offloading is the best option to reduce the burden of cellular networks. So, by aggregating existing indoor WiFi technology to the cellular network is increased the network capacity and provides better QoS to customers. In this article, we proposed and implement the LTE-WiFi aggregation system which is very similar to the 3GPP LWA system. Furthermore, the proposed system is integrated with the MCORD platform which is SDN, NFV, and cloud-based opensource solutions for providing a 5G environment. The implementation of the proposed system is based on the OpenAirInterface OAI software-defined radio (SDR) platform where WLAN AP is directly connected to eNodeB. The aggregation of both technologies is done at the PDCP layer. Moreover, we test our proposed system with three kinds of policies for UDP and TCP traffic known as LT E only, WiFi only and LTE-WiFi aggregated. The experimental result shows that our proposed LTE-WiFi aggregated system gives better performance and provides high bandwidth as compared to single LTE.
  * **Network In Network**
  `abstract`: We propose a novel deep network structure called "Network In Network" (NIN) to enhance model discriminability for local patches within the receptive field. The conventional convolutional layer uses linear filters followed by a nonlinear activation function to scan the input. Instead, we build micro neural networks with more complex structures to abstract the data within the receptive field. We instantiate the micro neural network with a multilayer perceptron, which is a potent function approximator. The feature maps are obtained by sliding the micro networks over the input in a similar manner as CNN; they are then fed into the next layer. Deep NIN can be implemented by stacking mutiple of the above described structure. With enhanced local modeling via the micro network, we are able to utilize global average pooling over feature maps in the classification layer, which is easier to interpret and less prone to overfitting than traditional fully connected layers. We demonstrated the state-of-the-art classification performances with NIN on CIFAR-10 and CIFAR-100, and reasonable performances on SVHN and MNIST datasets.
  * **Raman Spectrum of Graphite**
  `abstract`: Raman spectra are reported from single crystals of graphite and other graphite materials. Single crystals of graphite show one single line at 1575 cm−1. For the other materials like stress‐annealed pyrolitic graphite, commercial graphites, activated charcoal, lampblack, and vitreous carbon another line is detected at 1355 cm−1. The Raman intensity of this band is inversely proportional to the crystallite size and is caused by a breakdown of the k‐selection rule. The intensity of this band allows an estimate of the crystallite size in the surface layer of any carbon sample. Two in‐plane force constants are calculated from the frequencies.

* people that already should be in the database: `name`, `surname`, `affiliation`:
  * **Raman Laghari**: Bombay Institute Of Technology, Physics, BSc
  * **Barbaros Yoğurçuoğlu**: Institut d'Etudes Politiques de Paris, Political Sciences, MSc
  * **Giuseppe Mendoza**: University of Palermo, Medicine, MBBS
  * **Natalia Mendoza**: Interamerican University of Panama, Bioinformatics, MSc

**Comment by Tubagc** [comment]
Aysel Gümrükçü
