### ISSUE TITLE
User Recommendations Follow Bug 

### ISSUE THREAD

**Issue by UkcaGreen** [bounswe/bounswe2020group6#323]
I have discovered a bug in frontend branch.

**Bug description:**
When user tries to follow users by using recommendations part at the right side of the page. In some cases, profile sider information is switched with the followed user's information (name, surname, profile picture).

**How to reproduce:**
Login and open [home](http://www.akademise.ml/home), [followers](http://www.akademise.ml/list/followers) or [following](http://www.akademise.ml/list/following). And try to follow those users by clicking same follow button several times. (be careful you might be already following those users since currently our product might recommend a user that you already follow).
And hopefully you will experince the bug that I stated.

**How long it lasts:**
After page change or refresh bug disappears

**Comment by cemreefe** [comment]
I am looking into this issue.

**Comment by cemreefe** [comment]
Turns out the function using the `add follow` endpoint was making use of `get profile` to update some values, setting local environment variables to those of the user whose profile is followed.

I have fixed this bug on my [bug fix commit](https://github.com/bounswe/bounswe2020group6/commit/72947292614de30a12889105d7ec0267eccd783a) committed directly into the frontend branch.
