### ISSUE TITLE
Project Creation Bug in Android

### ISSUE THREAD

**Issue by cihatkapusuz** [bounswe/bounswe2020group6#417]
There is a bug about creating a new project. Request returns 500 internal server error but the project is created when the application is restarted.

How to reproduce:

- Open the latest version of the android application in android-projectcreation branch.  
- Enter necessary informations to create a project, then press 'DONE' button.

Toast says the project is not created and returned 500 error but the new project can be seen after restarting the application.

**Comment by EnesToptas** [comment]
The reason of bug was the change of field types at the database. 

The status field of project table had boolean type earlier, then we changed it to integer type. After this change, new requests from frontend and mobile both had the status field as integer. Database could successfuly add the new project into project table, but elasticsearch part was problematic.

Since there were already some projects in elasticsearch's "posts" index, and there, projects had their status fields of type boolean, newly created projects with status fields of type integer was not compatible with the older ones, and this threw an error. Due to this error, the response had the http status code 500.

We fixed this by removing earlier projects from elastichsearch's index.
